const fitnessScopes = {
  FITNESS_ACTIVITY_READ:
    'https://www.googleapis.com/auth/fitness.activity.read',
  FITNESS_ACTIVITY_WRITE:
    'https://www.googleapis.com/auth/fitness.activity.write',
  FITNESS_LOCATION_READ:
    'https://www.googleapis.com/auth/fitness.location.read',
  FITNESS_LOCATION_WRITE:
    'https://www.googleapis.com/auth/fitness.location.write',
  FITNESS_BODY_READ: 
    'https://www.googleapis.com/auth/fitness.body.read',
  FITNESS_BODY_WRITE: 
    'https://www.googleapis.com/auth/fitness.body.write',
  FITNESS_NUTRITION_READ:
    'https://www.googleapis.com/auth/fitness.nutrition.read',
  FITNESS_NUTRITION_WRITE:
    'https://www.googleapis.com/auth/fitness.nutrition.write',
  FITNESS_BLOOD_PRESSURE_READ:
    'https://www.googleapis.com/auth/fitness.blood_pressure.read',
  FITNESS_BLOOD_PRESSURE_WRITE:
    'https://www.googleapis.com/auth/fitness.blood_pressure.write',
  FITNESS_BLOOD_GLUCOSE_READ:
    'https://www.googleapis.com/auth/fitness.blood_glucose.read',
  FITNESS_BLOOD_GLUCOSE_WRITE:
    'https://www.googleapis.com/auth/fitness.blood_glucose.write',
  FITNESS_OXYGEN_SATURATION_READ:
    'https://www.googleapis.com/auth/fitness.oxygen_saturation.read',
  FITNESS_OXYGEN_SATURATION_WRITE:
    'https://www.googleapis.com/auth/fitness.oxygen_saturation.write',
  FITNESS_BODY_TEMPERATURE_READ:
    'https://www.googleapis.com/auth/fitness.body_temperature.read',
  FITNESS_BODY_TEMPERATURE_WRITE:
    'https://www.googleapis.com/auth/fitness.body_temperature.write',
  FITNESS_REPRODUCTIVE_HEALTH_READ:
    'https://www.googleapis.com/auth/fitness.reproductive_health.read',
  FITNESS_REPRODUCTIVE_HEALTH_WRITE:
    'https://www.googleapis.com/auth/fitness.reproductive_health.write',
  FITNESS_SLEEP_READ:
    'https://www.googleapis.com/auth/fitness.sleep.read',
  FITNESS_SLEEP_WRITE:
    'https://www.googleapis.com/auth/fitness.sleep.write',
  FITNESS_HEART_RATE_READ:
    'https://www.googleapis.com/auth/fitness.heart_rate.read',
  FITNESS_HEART_RATE_WRITE:
    'https://www.googleapis.com/auth/fitness.heart_rate.write'
}

export default fitnessScopes
