name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Install dependencies
        run: |
          corepack enable
          yarn install
      
      - name: Bump version
        id: version
        run: |
          npm version ${{ inputs.version_bump }} --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "✅ Version bumped to $NEW_VERSION"
      
      - name: Create and push tag
        run: |
          git tag -a "v${{ env.NEW_VERSION }}" -m "Release v${{ env.NEW_VERSION }}"
          git push origin "v${{ env.NEW_VERSION }}"
          echo "✅ Tag v${{ env.NEW_VERSION }} created and pushed"
      
      - name: Get previous version tag
        id: prev_tag
        run: |
          # Get second-to-last tag (since we just created the new one)
          PREV_TAG=$(git tag -l --sort=-v:refname | grep -v "v${{ env.NEW_VERSION }}" | head -n 1)
          echo "tag=$PREV_TAG" >> $GITHUB_OUTPUT
          if [ -n "$PREV_TAG" ]; then
            echo "📌 Previous tag: $PREV_TAG"
          else
            echo "📌 No previous tag found"
          fi
      
      - name: Create pre-release on GitHub
        id: create_release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ -n "${{ steps.prev_tag.outputs.tag }}" ]; then
            gh release create "v${{ env.NEW_VERSION }}" \
              --title "v${{ env.NEW_VERSION }}" \
              --generate-notes \
              --notes-start-tag "${{ steps.prev_tag.outputs.tag }}" \
              --prerelease
          else
            gh release create "v${{ env.NEW_VERSION }}" \
              --title "v${{ env.NEW_VERSION }}" \
              --notes "Initial release of react-native-google-fit" \
              --prerelease
          fi
          
          echo "✅ Pre-release created"
      
      - name: Get release notes from GitHub
        id: release_notes
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release view "v${{ env.NEW_VERSION }}" --json body --jq '.body' > /tmp/release_notes.md
          echo "✅ Release notes retrieved"
      
      - name: Generate changelog entry
        id: changelog
        run: |
          echo "### [${{ env.NEW_VERSION }}] - $(date +%Y-%m-%d)" > /tmp/changelog_entry.md
          echo "" >> /tmp/changelog_entry.md
          echo "#### Changes" >> /tmp/changelog_entry.md
          
          # Extract just the commits from the release notes (skip the header)
          tail -n +3 /tmp/release_notes.md >> /tmp/changelog_entry.md
          
          echo "" >> /tmp/changelog_entry.md
          echo "" >> /tmp/changelog_entry.md
          
          echo "✅ Changelog entry generated"
      
      - name: Update CHANGELOG.md
        run: |
          head -n 5 CHANGELOG.md > /tmp/changelog_new.md
          echo "" >> /tmp/changelog_new.md
          cat /tmp/changelog_entry.md >> /tmp/changelog_new.md
          tail -n +6 CHANGELOG.md >> /tmp/changelog_new.md
          mv /tmp/changelog_new.md CHANGELOG.md
          
          echo "✅ CHANGELOG.md updated"
      
      - name: Generate PR body
        id: pr_body
        run: |
          {
            echo "body<<EOF"
            echo "## Release v${{ env.NEW_VERSION }}"
            echo ""
            echo "This PR prepares the release for version **v${{ env.NEW_VERSION }}**."
            echo ""
            echo "🔖 **Pre-release created:** [v${{ env.NEW_VERSION }}](https://github.com/${{ github.repository }}/releases/tag/v${{ env.NEW_VERSION }})"
            echo ""
            echo "### Changes in this release:"
            echo ""
            cat /tmp/release_notes.md
            echo ""
            echo "---"
            echo ""
            echo "### Checklist before merging:"
            echo "- [ ] Version bump is correct"
            echo "- [ ] CHANGELOG.md is properly updated"
            echo "- [ ] Release notes look good"
            echo "- [ ] All tests pass"
            echo "- [ ] Ready to publish to npm"
            echo ""
            echo "**Note:** Once this PR is merged, the pre-release will be automatically:"
            echo "- ✅ Marked as a full release"
            echo "- 📦 Published to npm"
            echo "EOF"
          } >> $GITHUB_OUTPUT
      
      - name: Create release branch
        run: |
          BRANCH_NAME="release/v${{ env.NEW_VERSION }}"
          git checkout -b $BRANCH_NAME
          git add package.json CHANGELOG.md
          git commit -m "chore: prepare release v${{ env.NEW_VERSION }}"
          git push origin $BRANCH_NAME
          
          echo "RELEASE_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
          echo "✅ Release branch created: $BRANCH_NAME"
      
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --base master \
            --head ${{ env.RELEASE_BRANCH }} \
            --title "Release v${{ env.NEW_VERSION }}" \
            --body "${{ steps.pr_body.outputs.body }}"
          
          echo "✅ Pull request created"
          echo ""
          echo "🎉 Release preparation complete!"
          echo "📝 Review the PR and merge when ready to publish"

