name: Publish to npm

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: |
          corepack enable
          yarn install
      
      - name: Get version from release tag
        id: version
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"  # Remove 'v' prefix
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV
          echo "📦 Version: $VERSION"
      
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish
          echo "✅ Published to npm"
      
      - name: Comment on release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release comment "${{ github.event.release.tag_name }}" --body \
            "🎉 **Package published to npm!**
            
            📦 **npm package:** [react-native-google-fit@${{ env.NEW_VERSION }}](https://www.npmjs.com/package/react-native-google-fit/v/${{ env.NEW_VERSION }})
            
            The package is now available and can be installed with:
            \`\`\`bash
            npm install react-native-google-fit@${{ env.NEW_VERSION }}
            # or
            yarn add react-native-google-fit@${{ env.NEW_VERSION }}
            \`\`\`"
          
          echo "✅ Release comment posted"
      
      - name: Summary
        run: |
          echo "🎉 npm publish complete!"
          echo ""
          echo "📋 Summary:"
          echo "  ✅ Version: ${{ env.NEW_VERSION }}"
          echo "  ✅ Release: https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }}"
          echo "  ✅ npm: https://www.npmjs.com/package/react-native-google-fit/v/${{ env.NEW_VERSION }}"

