name: Release Published

on:
  release:
    types: [published]

jobs:
  create-version-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get version from release
        id: version
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"  # Remove 'v' prefix
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV
          echo "📦 Version: $VERSION"

      - name: Get release notes
        id: release_notes
        run: |
          echo '${{ github.event.release.body }}' > /tmp/release_notes.md
          echo "✅ Release notes retrieved"

      - name: Update package.json
        run: |
          # Update version in package.json
          node -e "
            const fs = require('fs');
            const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
            pkg.version = '${{ env.NEW_VERSION }}';
            fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
          "
          echo "✅ package.json updated to v${{ env.NEW_VERSION }}"

      - name: Generate changelog entry
        run: |
          echo "### [${{ env.NEW_VERSION }}] - $(date +%Y-%m-%d)" > /tmp/changelog_entry.md
          echo "" >> /tmp/changelog_entry.md
          cat /tmp/release_notes.md >> /tmp/changelog_entry.md
          echo "" >> /tmp/changelog_entry.md
          echo "" >> /tmp/changelog_entry.md

          echo "✅ Changelog entry generated"

      - name: Update CHANGELOG.md
        run: |
          # Insert new entry after the header (line 5)
          head -n 5 CHANGELOG.md > /tmp/changelog_new.md
          echo "" >> /tmp/changelog_new.md
          cat /tmp/changelog_entry.md >> /tmp/changelog_new.md
          tail -n +6 CHANGELOG.md >> /tmp/changelog_new.md
          mv /tmp/changelog_new.md CHANGELOG.md

          echo "✅ CHANGELOG.md updated"

      - name: Create PR branch
        run: |
          BRANCH_NAME="release-pr/v${{ env.NEW_VERSION }}"
          git checkout -b $BRANCH_NAME
          git add package.json CHANGELOG.md
          git commit -m "chore: release v${{ env.NEW_VERSION }}"
          git push origin $BRANCH_NAME

          echo "PR_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
          echo "✅ PR branch created: $BRANCH_NAME"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Create PR body
          echo "## Release v${{ env.NEW_VERSION }}" > /tmp/pr_body.md
          echo "" >> /tmp/pr_body.md
          echo "This PR updates the version to **v${{ env.NEW_VERSION }}** and updates the changelog." >> /tmp/pr_body.md
          echo "" >> /tmp/pr_body.md
          echo "**Release:** [v${{ env.NEW_VERSION }}](https://github.com/${{ github.repository }}/releases/tag/v${{ env.NEW_VERSION }})" >> /tmp/pr_body.md
          echo "" >> /tmp/pr_body.md
          echo "### Changes in this release:" >> /tmp/pr_body.md
          echo "" >> /tmp/pr_body.md
          cat /tmp/release_notes.md >> /tmp/pr_body.md
          echo "" >> /tmp/pr_body.md
          echo "---" >> /tmp/pr_body.md
          echo "" >> /tmp/pr_body.md
          echo "### What this PR does:" >> /tmp/pr_body.md
          echo "- Bumps version in package.json to ${{ env.NEW_VERSION }}" >> /tmp/pr_body.md
          echo "- Updates CHANGELOG.md with release notes" >> /tmp/pr_body.md
          echo "" >> /tmp/pr_body.md
          echo "**Note:** Once this PR is merged, the npm package will be automatically published." >> /tmp/pr_body.md

          gh pr create \
            --base master \
            --head ${{ env.PR_BRANCH }} \
            --title "Release v${{ env.NEW_VERSION }}" \
            --body-file /tmp/pr_body.md

          echo "Pull request created"
